plugins { id 'com.android.application' }

android { namespace 'com.senseultra.shizuku'; compileSdk 35
    defaultConfig { applicationId 'com.senseultra.shizuku'; minSdk 26; targetSdk 35; versionCode 1; versionName '1.0.0' }
}

dependencies {
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
}
